# Generated by Django 4.1.4 on 2022-12-27 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='fecha_creacion',
            new_name='fc',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='fecha_modificacion',
            new_name='fm',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_creacion',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario_modificacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
